return {
	-- "stevearc/conform.nvim",
	-- event = { "BufReadPre", "BufNewFile" },
	-- config = function()
	-- 	local conform = require("conform")

	-- 	conform.setup({
	-- 		formatters_by_ft = {
	-- 			javascript = { "prettier" },
	-- 			typescript = { "prettier" },
	-- 			javascriptreact = { "prettier" },
	-- 			typescriptreact = { "prettier" },
	-- 			css = { "prettier" },
	-- 			scss = { "prettier" },
	-- 			html = { "prettier" },
	-- 			json = { "prettier" },
	-- 			markdown = { "prettier" },
	-- 			lua = { "stylua" },
	-- 		},
	-- 		formatters = {
	-- 			prettier = {
	-- 				prepend_args = {
	-- 					"--single-quote true",
	-- 					"--jsx-single-quote false",
	-- 					"--tab-width 2",
	-- 					"--print-width 80",
	-- 					"--use-tabs false",
	-- 					"--trailing-comma es5",
	-- 					"--arrow-parens avoid",
	-- 				},
	-- 			},
	-- 		},
	-- 		format_on_save = {
	-- 			-- I recommend these options. See :help conform.format for details.
	-- 			lsp_fallback = true,
	-- 			async = false,
	-- 			timeout_ms = 3000,
	-- 		},
	-- 	})

	-- 	-- Mappings
	-- 	vim.keymap.set({ "n", "v" }, "<leader>f", function()
	-- 		conform.format({
	-- 			lsp_fallback = true,
	-- 			async = false,
	-- 			timeout_ms = 3000,
	-- 		})
	-- 	end, { desc = "Format file or range" })
	-- end,
}
